<a href="https://colab.research.google.com/github/DAclarissememba-png/DAclarissememba/blob/main/Syntax_display.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
fruits = {"apple", "banana", "cherry"}
print(fruits)    # order may be different each time

{'banana', 'apple', 'cherry'}

In [ ]:
fruits = {"apple", "banana", "apple"}
print(fruits)

{'banana', 'apple'}

In [ ]:
fruits = {"apple", "banana", "cherry"}
fruits.discard("banana")  # Removes it
fruits.discard("orange")
print(fruits)

{'apple', 'cherry'}

In [ ]:
a = {1, 2, 3}
b = {3, 4}
print((a.union(b)))

{1, 2, 3, 4}

In [ ]:
animals={"dog", "cat","bear"}
len(animals)

3

In [ ]:
student = {
   "name": "Ali",
   "age": 20,
  "course": "Python"
}
print(student)

{'name': 'Ali', 'age': 20, 'course': 'Python'}

In [ ]:
print(student["name"])          # Ali
print(student.get("age"))       # 20

Ali
20

In [ ]:
import pandas as pd
numbers = pd.Series([10, 20, 30, 40])
print (numbers)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
data = {
   "Name": ["Tom", "Anna", "Ravi"],
  "Age":  [25,     30,    22]
}
print(data)

{'Name': ['Tom', 'Anna', 'Ravi'], 'Age': [25, 30, 22]}

In [ ]:
df = pd.DataFrame(data)
print (df)

   Name  Age
0   Tom   25
1  Anna   30
2  Ravi   22

In [ ]:
isinstance(df, pd.DataFrame)

True

In [ ]:
!pip --version

pip 24.1.2 from /usr/local/lib/python3.12/dist-packages/pip (python 3.12)

In [ ]:
import pandas as pd
data = {
   "calories": [420, 380, 390],
   "duration": [50, 40, 45]
}
#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
# Connect this notebook to your Google Drive
from google. colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student.csv

In [ ]:
df = pd.read_csv('student.csv')
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female